---
- name: Vyos Network Config
  hosts: vyos
  gather_facts: no
  become: yes
  vars_prompt:
    - name: password
      prompt: "Please enter the new Vyos password"
      private: true
  tasks:
    - name: Set Password Hash
      set_fact:
        password_hash: "{{ password | password_hash('sha512') }}"
    - name: Load Config from template
      template:
        src: config.boot.j2
        dest: /config/config.boot
        mode: "0775"
        owner: root
        group: vyattacfg
    - name: Bounce and end
      shell: nohup bash -c "/usr/bin/sleep 5 && /usr/sbin/shutdown -r now" >/dev/null 2>&1 &